// Generated by https://quicktype.io

export interface HomePage {
    groups: Group[];
}

export interface Group {
    groupName:   string;
    leadFaculty: LeadFaculty;
    users:       UserElement[];
}

export interface LeadFaculty {
    firstName: string;
    lastName:  string;
}

export interface UserElement {
    user: User;
}

export interface User {
    firstName: string;
    lastName:  string;
    role:      string;
    isActive:  boolean;
}
